name: Run Unit Test via Pytest  
  
on: [push]  
  
jobs:  
  build:  
  # runs ubuntu 22.04
    runs-on: ubuntu-22.04
    strategy:  
      matrix:  
        python-version: ["3.7", "3.8", "3.9"]
        #, "3.7", "3.8", "3.9"]  
  
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: Install dependencies  
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install ".[tempy]"
          pip install pytest
          pip install coverage
      - name: Test with pytest
        run: |
           coverage run -m pytest
      - name: Generate Coverage Report
        run: |
          coverage report -m